---
title: 'STATS 205: Homework Assignment 6'
author: "Brian Liu"
date: "6/14/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Solution to Problem 1

```{r}
library(datasets)
data(cars)
head(cars)
cars.supsmu = supsmu(cars$speed, cars$dist, bass = 0, span = "cv")
cars.supsmu2= supsmu(cars$speed, cars$dist, bass = 0, span = .30)
cars.supsmu3= supsmu(cars$speed, cars$dist, bass = 0, span = .05)
cars.supsmu4= supsmu(cars$speed, cars$dist, bass = 0, span = .175)

plot(x = cars$speed, y = cars$dist,
	main = "Stopping distances for various speeds",
	xlab = "Speed",	ylab = "Stopping Distance")
lines(x = cars.supsmu$x, y = cars.supsmu$y, col = "green")
lines(x = cars.supsmu2$x, y = cars.supsmu2$y, col = "red")
lines(x = cars.supsmu3$x, y = cars.supsmu3$y, col = "blue")
lines(x = cars.supsmu4$x, y = cars.supsmu4$y, col = "yellow")
legend(5, 110, legend=c("Friedman smoothed with 'cv' span", ".30 span", ".05 span", ".175 span"),
 col=c("green", "red", "blue", "yellow"), lty=1:1, cex=0.8)
```